"""empty message

Revision ID: 199ccb8de166
Revises: 
Create Date: 2020-10-31 18:22:54.598060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199ccb8de166'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sintomas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epidemiologico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_coleta', sa.DateTime(), nullable=True),
    sa.Column('doenca_associada', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('epidemiologico')
    op.drop_table('doencas')
    # ### end Alembic commands ###
