"""empty message

Revision ID: b4ec649bc09a
Revises: c008184e2145
Create Date: 2020-11-05 16:04:10.139476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4ec649bc09a'
down_revision = 'c008184e2145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doenca', 'nome',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('doenca', 'sintomas',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('epidemiologico', 'data_coleta',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('epidemiologico', 'doenca_associada',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epidemiologico', 'doenca_associada',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('epidemiologico', 'data_coleta',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('doenca', 'sintomas',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('doenca', 'nome',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
